apiVersion: v1
kind: Service
metadata:
  name: a
  labels:
    app: a
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  labels:
    app: a
spec:
  selector:
    matchLabels:
      app: a
  replicas: 1
  template:
    metadata:
      labels:
        app: a
    spec:
      imagePullSecrets:
        - name: default-registry-secret
      containers:
      - name: nginx
        image: {{ .Values.repository }}/{{ .Values.servicea.app }}:{{ .Values.servicea.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:
            cpu: 10m
            memory: 10Mi
        command: ["/myapp-1"]
        args: ["--downstream-addr", "$(DOWNSTREAM_ADDR)", "--headers", "$(HEADERS)"]
        env:
        - name: DOWNSTREAM_ADDR
          value: "b"
        - name: HEADERS
          value: "x-request-id"
        ports:
        - containerPort: 8080
