apiVersion: v1
kind: Service
metadata:
  name: bak
  labels:
    app: bak
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
    app: bak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bak
  labels:
    app: bak
spec:
  selector:
    matchLabels:
      app: bak
  replicas: 1
  template:
    metadata:
      labels:
        app: bak
    spec:
      imagePullSecrets:
        - name: default-registry-secret
      containers:
      - name: nginx
        image: {{ .Values.repository }}/{{ .Values.serviceb.app }}:{{ .Values.serviceb.tag }}
        imagePullPolicy: Always
        command: ["/myapp-2"]
        args: ["--downstream-addr", "$(DOWNSTREAM_ADDR)", "--headers", "$(HEADERS)"]
        env:
        - name: DOWNSTREAM_ADDR
          value: "c"
        - name: HEADERS
          value: "x-request-id"
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 100Mi